### ISSUE TITLE
Missing html svg

### ISSUE THREAD

**Issue by seanmrnda** [panekj/lapce-symbols#1]
![image](https://user-images.githubusercontent.com/45195351/198351603-e14bf504-486f-4f38-abff-99c949490214.png)

Html files are using `code-*.svg`.

**Comment by panekj** [comment]
There is no html icon

**Comment by seanmrnda** [comment]
> There is no html icon

It defaults to `code-red.svg`.

![image](https://user-images.githubusercontent.com/45195351/198353383-75aa25fb-b97d-4658-8560-e9b4f2c1262b.png)

---

>original repo screenshot

![image](https://user-images.githubusercontent.com/45195351/198353789-ce842e80-bf54-4a4d-8275-24c69edd14cd.png)
